import pandas as pd
data=("A':[1,2,3,4,5,5])
df=pd.DataFrame(data)
print("DataFrame")
print(df)
print("sum of each column
print(df.sum())
print("mean of each column")
print(df.mean())
print("median of each column")
print(df.median())
print("mode of each column")
print(df.mode())
print("minimum value of each column")
print(df.min())
print("maximumof value each column")
print(df.max())
print("count of null enteries of each column")
print(df.count())
print("variance of each column")
print(df.var())
print("standuard deviation of each column")
print(df.std())